logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
spring:
  security:
    oauth2:
      client:
        registration:
          salesforce:
            client-id: 3MVG9XgkMlifdwVBcasuMyH_JjRo489yuVN8kGE0kYpnUnPwAWYc8kCB2XLf.lprvyXbnbzJz391BPwXq3.PL
            client-secret: 2A8142BAD7531CF92EFD8C9AA000E4FFC3E22B3122FE95BED7C1338D371BDF25
            scope: api
            redirect-uri: https://integration-inbound-user-input-cafcf94ea457.herokuapp.com/login/oauth2/code/salesforce
            authorization-grant-type: authorization_code
        provider:
          salesforce:
            authorization-uri: https://adityachaudharycrm-dev-ed.develop.my.salesforce.com/services/oauth2/authorize
            token-uri: https://adityachaudharycrm-dev-ed.develop.my.salesforce.com/services/oauth2/token
            user-info-uri: https://adityachaudharycrm-dev-ed.develop.my.salesforce.com/services/oauth2/userinfo
            user-name-attribute: email